[project]
name = "natural-disasters-sdk"
version = "0.1.0"
description = "FEMA Natural Disasters API client"
requires-python = ">=3.10"
dependencies = [
  "requests>=2.31",
  "pydantic>=2.4",
]

[tool.pytest.ini_options]
testpaths = ["_tests"]